language: php
php:
 - 7.1
install: 
 - composer install

deploy:
  - provider: script
    script: bash scripts/deploy.sh staging
    on:
      all_branches: true
  - provider: script
    script: bash scripts/deploy.sh production
    on:
      branch: master