language: php
php:
 - 7.1
install: 
 - composer install

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh staging
    on:
      branches: preprod
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh production
    on:
      branch: master