language: php
php:
 - 7.1
install: 
 - composer install

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh staging
    on:
      branch: preprod
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh production
    on:
      branch: master

  - provider: elasticbeanstalk
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    region: "us-east-1"
    app: "PHP"
    env: "Php-env"
    bucket_name: "elasticbeanstalk-us-east-1-342247925588"
    on:
      branch: preprod
